# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bcor_open <- function(filename, read_header = TRUE) {
    .Call(`_rbcor_bcor_open`, filename, read_header)
}

bcor_get_meta <- function(bcor_ptr) {
    .Call(`_rbcor_bcor_get_meta`, bcor_ptr)
}

bcor_read_corr <- function(bcor_ptr, snps = NULL) {
    .Call(`_rbcor_bcor_read_corr`, bcor_ptr, snps)
}

bcor_read_corr2 <- function(bcor_ptr, snps1, snps2) {
    .Call(`_rbcor_bcor_read_corr2`, bcor_ptr, snps1, snps2)
}

bcor_read_corr_sparse <- function(bcor_ptr, snps = NULL, threshold = 0.0) {
    .Call(`_rbcor_bcor_read_corr_sparse`, bcor_ptr, snps, threshold)
}

bcor_read_corr_sparse2 <- function(bcor_ptr, snps1, snps2, threshold = 0.0) {
    .Call(`_rbcor_bcor_read_corr_sparse2`, bcor_ptr, snps1, snps2, threshold)
}

bcor_read_corr_packed <- function(bcor_ptr, snps = NULL) {
    .Call(`_rbcor_bcor_read_corr_packed`, bcor_ptr, snps)
}

